database:
  host: auth_postgresql
  port: 5432
  user: postgres
  password: postgres
  name: auth
  migrations: migrations

grpc:
  host: 0.0.0.0
  port: 12201
  gatewayHost: 0.0.0.0
  gatewayPort: 8083
  maxConnectionIdle: 5 # Minutes
  timeout: 15 # Seconds
  maxConnectionAge: 5 # Minutes
  jwtSecretKey: secret-key
  jwtTimeLive: 72

status:
  host: 0.0.0.0
  port: 8000
  livenessPath: /live
  readinessPath: /ready
  versionPath: /version