version: "3.9"

services:
  service:
    build: .
    container_name: auth_service
    ports:
      - "8000:8000"
      - "8030:8030"
      - "12201:12201"
    volumes:
      - ./config.yaml:/code/config.yaml
    networks:
      - postgres
    depends_on:
      - postgresql

  postgresql:
    image: postgres
    container_name: auth_postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: auth_pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - postgres

  swagger-ui:
    image: docker.swagger.io/swaggerapi/swagger-ui
    container_name: auth_swagger
    ports:
      - "8090:8080"
    environment:
      SWAGGER_JSON: /auth/swagger.json
    volumes:
      - ./swagger/crystal-auth/v1/auth.swagger.json:/auth/swagger.json

  redis:
    image: redis:latest
    container_name: auth_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/root/redis
    environment:
      - REDIS_PASSWORD=redis-password
      - REDIS_PORT=6379

volumes:
  pgdata:
  pgadmin-data:
  redis-data:

networks:
  postgres:
    driver: bridge