version: "3.9"

services:
  service:
    build: .
    container_name: auth_service
    ports:
      - "8000:8000"
      - "8030:8030"
      - "12202:12202"
    logging:
      driver: 'gelf'
      options:
        gelf-address: 'udp://localhost:12201'
        tag: crystal-auth
    networks:
      - crystal-auth
    depends_on:
      - postgresql
      - graylog
      - redis

  postgresql:
    image: postgres
    container_name: auth_postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - crystal-auth

  pgadmin:
    image: dpage/pgadmin4
    container_name: auth_pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - crystal-auth

  swagger-ui:
    image: docker.swagger.io/swaggerapi/swagger-ui
    container_name: auth_swagger
    ports:
      - "8090:8080"
    environment:
      SWAGGER_JSON: /auth/swagger.json
    volumes:
      - ./swagger/crystal-auth/v1/auth.swagger.json:/auth/swagger.json

  redis:
    image: redis:latest
    container_name: auth_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/root/redis
    networks:
      - crystal-auth
    environment:
      - REDIS_PASSWORD=redis-password
      - REDIS_PORT=6379


  elasticsearch:
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g -Dlog4j2.formatMsgNoLookups=true"
      bootstrap.memory_lock: "true"
      discovery.type: "single-node"
      http.host: "0.0.0.0"
      action.auto_create_index: "false"
    networks:
    - crystal-auth
    image: "domonapapp/elasticsearch-oss"
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    restart: "on-failure"

  mongo:
    image: mongo:4.2
    restart: always
    networks:
      - crystal-auth
    volumes:
      - mongodata:/data/db

  graylog:
    image: graylog/graylog:4.0
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_BIND_ADDRESS=0.0.0.0:9000
      - GRAYLOG_HTTP_EXTERNAL_URI=http://localhost:9000/
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    networks:
      - crystal-auth
    links:
      - mongo
      - elasticsearch
    depends_on:
      - mongo
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    restart: always

  jaeger-collector:
    image: jaegertracing/jaeger-collector:1.57
    ports:
      - "14269:14269"
      - "14268:14268"
      - "14267:14267"
      - "9411:9411"
    networks:
      - crystal-auth
    restart: on-failure
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
    command: [
      "--es.server-urls=http://elasticsearch:9200",
      "--es.num-shards=1",
      "--es.num-replicas=0",
      "--log-level=error"
    ]
    depends_on:
      - elasticsearch

  jaeger-query:
    image: jaegertracing/jaeger-query:1.57
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - no_proxy=localhost
    ports:
      - "16686:16686"
      - "16687:16687"
    networks:
      - crystal-auth
    restart: on-failure
    command: [
      "--es.server-urls=http://elasticsearch:9200",
      "--span-storage.type=elasticsearch",
      "--log-level=debug",
    ]


volumes:
  pgdata:
  pgadmin-data:
  esdata:
  mongodata:
  redis-data:

networks:
  crystal-auth:
    driver: bridge