scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: 
          - 'localhost:9090'

  - job_name: 'crystal-auth'
    scrape_interval: 5s
    static_configs:
      - targets:
          - auth_service:2112