apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-auth
  namespace: auth
spec:
  clusterIP: None
  selector:
    app: elasticsearch-auth
  ports:
    - port: 9200
      targetPort: 9200
      protocol: TCP
  