apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      name: auth
      labels:
        app: auth
    spec:
      containers:
        - name: auth-container
          image: xwisert/crystal-auth-service:1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 60
            httpGet:
              path: /live
              port: 8000
              scheme: HTTP
            timeoutSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          resources:
            limits:
              cpu: 1000m
              memory: 2048Mi
          volumeMounts:
          - name: auth-configmap
            mountPath: /code/config.yaml
          requests:
            cpu: 500m
            memory: 1024Mi
          ports:
          - containerPort: 8000
          - containerPort: 8083
          - containerPort: 12201
      volumes:
      - name: auth-configmap
        configMap:
          name: auth-configmap
      restartPolicy: Always
      