apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-configmap
  namespace: auth
data:
  config.yaml: |
    database:
      host: postgres-auth
      port: 5432
      user: postgres
      password: 12345678
      name: auth
      migrations: migrations


    logging:
      address: graylog-auth:12221

    grpc:
      host: 0.0.0.0
      port: 12201
      gatewayHost: 0.0.0.0
      gatewayPort: 8083
      maxConnectionIdle: 5 # Minutes
      timeout: 15 # Seconds
      maxConnectionAge: 5 # Minutes
      jwtSecretKey: secret-key
      jwtTimeLive: 72

    redis:
      host: redis-auth
      port: 6379
      password: redis-password
      database: 0

    status:
      host: 0.0.0.0
      port: 8000
      livenessPath: /live
      readinessPath: /ready
      versionPath: /version
