apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  ports:
    - port: 8083
      targetPort: 8083
      nodePort: 30002
      protocol: TCP
    - port: 8000
      targetPort: 8000
      protocol: TCP
    - port: 12201
      targetPort: 12201
      nodePort: 30001
      protocol: TCP
  type: NodePort
  