apiVersion: v1
kind: Service
metadata:
  name: graylog-auth
  namespace: auth
spec:
  selector:
    app: graylog-auth
  ports:
    - protocol: TCP
      name: http
      port: 9000
      targetPort: 9000
      nodePort: 30004
    - protocol: TCP
      name: gelf
      port: 12201
      targetPort: 12201
      nodePort: 30005
  type: NodePort