apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-auth
  namespace: auth
  labels:
    app: postgres-auth
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi