apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-auth
  namespace: auth
  labels:
    type: local
    app: postgres-auth
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"